[package]
name = "adrian"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8.2", features = [ "runtime-tokio", "mysql", "chrono"] }
chrono = "0.4.34"
regex = "1.10.3"
once_cell = "1.19.0"
serde_json = "1.0.132"
serde = { version = "1.0.210", features = ["derive"] }
futures = "0.3.31"