[package]
name = "web_server"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/fooooter/web_server_poc"
license = "LGPL-3.0-or-later"

[dependencies]
tokio = { version = "1.41.1", features = ["full"] }
chrono = "0.4.34"
regex = "1.10.3"
serde_json = "1.0.132"
serde = { version = "1.0.210", features = ["derive"] }
glob = "0.3.1"
mime_guess = "2.0.5"
flate2 = "1.0.34"
libloading = "0.8.5"
bytes = "1.8.0"
