name: Build for aarch64-unknown-linux-gnu

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    container: quay.io/pypa/manylinux2014_aarch64

    steps:
    - name: Build
      run: cargo build --verbose=
